version: "3.8"
services:
  team_app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - team_db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: team-app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: team_db
      DB_PORT: 3306
    networks:
      - app_network

  team_nginx:
    build:
      context: ./docker-nginx/.
    volumes:
    - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: team_app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - team_app
    networks:
      - app_network

  team_db:
    image: mysql:5
    restart: always
    environment: 
      - MYSQL_ROOT_HOST=team_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=team
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      #- ./init.sql:/data/application/init.sql
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro
      - database_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network


volumes:
  database_mysql:

networks:
  app_network:
    driver: bridge
